# Directories for Input and Output Data
directories:
  source: "/Users/mrat0010/Documents/IJCV/Input/cam_1_N_video_20210315_132804.h264.avi"    # Path to the directory containing input videos.
  output: "/Users/mrat0010/Documents/IJCV/Output1/"   # Path to save the processed output videos.

# Configuration for Input Video Properties
source:
  resolution:                          # Resolution of the input video in pixels as [width, height].
    - 1920                             # Width of the input video in pixels.
    - 1080                             # Height of the input video in pixels.
  framerate: 30                        # Frame rate of the input video (frames per second).
  compressed_video: True              # Indicates if the input video is compressed.
  compression_info: ""                 # Filepath to the additional information document on compression.
  skip_frames: False                   # Skip and only process odd frames. To be used with deinterlaced videos if applicable. 


# Configuration for Output Video Properties
output:
  resolution:                          # Resolution of the output video in pixels as [width, height].
    - 1280                             # Width of the output video in pixels.
    - 720                              # Height of the output video in pixels.
  codec: "DIVX"                        # Codec used for compressing the output video.
  show: True                           # Whether to display the video output during processing.
  save: True                           # Whether to save the processed video output to a file.

# Insect Tracking Configuration
insect_tracking:
  labels: 
    - "honeybee"                       # Human-readable labels for tracked insect classes.
    - "hoverfly"
    - "moth"

  classes:                             # Class IDs corresponding to tracked insect classes.
    - 0
    - 1
    - 2 

  prediction_method:                   # Algorithm for predicting insect movement. Comment out the lines not in use.
    - "ConstantVelocity"               # Constant velocity model.
    # - "KalmanFilter"                   # Kalman Filter
    # - "ExtendedKalmanFilter"           # Extended Kalman Filter

  assignment_method:                   # Algorithm for assigning insect detections to tracks. Comment out the lines not in use.
    - "HungarianMethod"                # Linear Sum Assignment or Hungarian Method
    # - "ABP"                            # Association by Proximity

  detectors:                           # List of insect detection methods used.
    - dl_detection                     # Primary AI-based detection model.
    - fgbg_detection                   # Foreground-based blob detection.
    - secondary_verification           # Secondary AI-based detection model for additional validation of new insect detections.

  detection_interval: 300              # Number of frames between re-evaluating insect positions.
  min_blob_area: 5                     # Minimum area (in pixels) for detected insect blobs.
  max_blob_area: 5000                  # Maximum area (in pixels) for detected insect blobs.
  insect_boundary_extension: 2.5       # Scale factor to extend the boundary around detected insects.
  iou_threshold: 0                     # IoU threshold for validating insect detections.
  max_occlusions: 100                  # Maximum frames an insect can remain occluded and still be tracked.
  max_occlusions_on_flower: 300        # Maximum frames a flower can remain occluded.
  jump_distance:                       # Maximum distance (in pixels) insects can move between frames.
    - 200                              # Maximum horizontal jump distance allowed with AI detection.
    - 35                               # Maximum vertical jump distance allowed with foreground detection. Default: 35
  min_track_length: 5                  # Minimum number of frames an insect must be tracked to be considered valid.
  edge_analysis:                # Analysis of insect behavior near the frame edges.
    edge_pixels: 50                    # Number of pixels near the frame edges considered as border cases.
    max_edge_occlusions: 32              # Maximum occlusion frames near the edge of the frame.
    continious_analysis: True         # Enable continious analysis of edge insects.
    compressed_video_time_jump: 100    # Time jump after which edge insects are re-evaluated in compressed videos.


  # Detector-Specific Properties
  detector_properties:
    dl_detection:
      model: "/Users/mrat0010/Documents/IJCV/Models/20250117/insects_best_s.pt"  # Path to the primary detection model.
      detection_confidence: 0.5                       # Minimum confidence score for valid detections.
      iou_threshold: 0                                # IoU threshold for validation.
      image_size:                                     # Size of the input image for the primary detection model.
        - 864                                         # Width of the input image in pixels.   
        - 480                                         # Height of the input image in pixels.     

    secondary_verification:
      model:  "/Users/mrat0010/Documents/IJCV/Models/20250117/insects_best_l.pt" # Path to the secondary detection model.
      detection_confidence:                           # Minimum confidence scores for validating insect classes.
        - 0.5                                         # Confidence score for primary class (honeybees).
        - 0.3                                         # Confidence score for secondary class (hoverflies).
        - 0.3                                         # Confidence score for tertiary class (moths).
      black_pixel_threshold: 0.5                      # Threshold for black pixel density in detected regions.
      image_size:                                     # Size of the input image for the secondary detection model.  
        - 640                                         # Width of the input image in pixels.         
        - 640                                         # Height of the input image in pixels.

    fgbg_detection:
      model: 
      - 'FrameDifference'                             # Calculate the difference between consecutive frames.
      # - 'MOG2'                                        # Gaussian Mixture-based Background/Foreground Segmentation.
      downscale_factor: 1                             # Scaling factor for downsampling frames during preprocessing.
      dilate_kernel_size: 8                           # Kernel size for dilation operation during blob detection. (Default: 8)
      movement_threshold: 120                          # Intensity threshold for detecting motion. (Default: 120)
      show: False                                     # Display the output of the foreground detection model.
      clean_detections: True                          # Compare detections made in adjacent frames to remove duplicates.

# Flower Tracking Configuration
flower_tracking:
  track: True                                        # Enable/disable flower tracking.
  labels: 
    - "flower"                                        # Human-readable labels for tracked flower classes.
  classes:                                            # Class IDs corresponding to flower classes.
    - 0
  detection_interval: 300                             # Number of frames between flower detection updates.
  border_extension: 1.75                              # Scale factor to extend boundaries for detected flowers.
  prediction_method: "ConstantVelocity"               # Algorithm for predicting flower movement.

  # Detector Properties for Flower Tracking
  detector_properties:
    model: "/Users/mrat0010/Documents/IJCV/Models/flowers.pt"             # Path to the flower detection model.
    detection_confidence: 0.1                         # Minimum confidence score for valid detections.
    iou_threshold: 0.5                                # IoU threshold for flower detection validation.
