directories:
  source: "./data/Blueberry/Input/"  # Path to the directory containing input videos.
  output: "./data/Blueberry/Output/"  # Path to save the processed output videos.

insects:
  classes: [0, 1, 2]                     # Class IDs for tracked insects.
  detectors:
    primary:
      model: "/Users/mrat0010/Documents/GitHub/Polytrack_PUB/data/yolov8_models/blueberry_bee.pt"  # Path to the primary insect detection model.
      detection_confidence: 0.2            # Minimum confidence score required for a detection.
      iou_threshold: 0                      # Intersection over Union (IoU) threshold for detections.
    
    secondary:
      use: True                         # Enable additional verification for new insect detections.
      model: "/Users/mrat0010/Documents/GitHub/Polytrack_PUB/data/yolov8_models/blueberry_bee.pt"  # Path to the secondary detection model.
      detection_confidence: [0.2, 0.2, 0.2] # Confidence thresholds for verifying different insect classes.
      black_pixel_threshold: 0.5           # Threshold for black pixel density in detection areas.

    foreground:
      downscale_factor: 1                  # Downscaling factor for input frames during preprocessing.
      dilate_kernel_size: 8                # Size of the dilation kernel used for blob detection.
      movement_threshold: 120              # Pixel intensity threshold for detecting movement.

  tracking:
    prediction_method: "ConstantVelocity" # Method used for predicting insect movements.
    min_blob_area: 5                     # Minimum area (in pixels) of a detected insect blob.
    max_blob_area: 5000                  # Maximum area (in pixels) of a detected insect blob.
    jump_distance: [200, 35]             # Maximum allowable distance (pixels) an insect can jump between frames [x, y].
    insect_boundary_extension: 2.5       # Boundary extension factor for insect regions.
    iou_threshold: 0                     # Intersection over Union (IoU) threshold for detections.

flowers:
  track: False                            # Whether to enable flower tracking.
  detector:
    model: "/Users/mrat0010/Documents/GitHub/Polytrack_PUB/data/yolov8_models/blueberry_flower.pt"  # Path to the flower detection model.
    detection_confidence: 0.1            # Minimum confidence score required for a detection.
    iou_threshold: 0.5                      # Intersection over Union (IoU) threshold for detections.
    classes: [0]                           # Class IDs for tracked flowers.
  labels: ["flower"]                     # Human-readable labels for tracked flower classes.
  tracking:
    detection_interval: 300              # Number of frames between flower detection updates.
    border_extension: 1.75               # Extension factor for flower detection boundaries.
    prediction_method: "ConstantVelocity" # Method used for predicting flower movements.

source:
  resolution: [1920, 1080]             # Resolution of the input videos in pixels [width, height].
  framerate: 30                        # Frame rate of the input video (frames per second).
  compressed_video: False                    # Whether the input video is compressed.
  compression_info: ""                 # Additional information about the compression format (if any).


output:
  video:
    resolution: [1280, 720]                # Resolution of the output videos in pixels [width, height].
    codec: "DIVX"                          # Codec used for video compression in the output.
    show: True                             # Whether to display the video output during processing.
    save: True                             # Whether to save the processed video output to a file.

  tracking:
    insect_labels: ["honeybee"]          # Insects to be tracked in the output video.
    max_occlusions: 300                  # Maximum number of frames an insect can remain occluded.
    max_edge_occlusions: 32              # Maximum number of frames an insect can be occluded near the edge.
    max_occlusions_on_flower: 300        # Maximum number of frames a flower can remain occluded.
    edge_pixels: 40                      # Number of pixels near the edge of the frame considered for edge cases.


  